### ISSUE TITLE
Eline, emeğine sağlık!

### ISSUE THREAD

**Issue by batuhanozkandev** [ketvolkan/Flutter-Stajerimi-Bul-App#1]
Her şeyden önce emeğine sağlık!

1. Widgetları performansı artırmak açısından extract method yerine 'extract widget' yaparsan daha sağlıklı olur.

> ❌ `appBar: _buildAppBar,`
> ✅ `appBar: CustomAppBar(),`

2. AppBar için her sayfada kod yazmak yerine bu widgetı bir model component haline getirebilir ve kod tekrarından kurtulabilirsin.

3. Padding, sizedbox, gibi componentler için 'num' üzerinde bir extension yazarak kod kaliteni artırabilirsin.

En çok gözüme çarpanlar bunlardı. Umarım feedback olarak alır ve faydalanırsın. Güzel kodlarının devamını bekliyoruz!

**Comment by ketvolkan** [comment]
İncelemen için çok teşekkürler madde madde ilerleyip açıklama yapacağım.Aslında bu proje benim ilk flutter projelerim arasında dönüp baktığımda eksiklerime gülüyorum bazen ne kadar yol kat ettiğimi görüyorum tabikide hala bilmediğim taraflar var ve incelemen bu konuda benim için yararlı oldu tekrardan teşekkürler.

1. Dediğin gibi aslında CustomAppBar olarak dışardan oluşturduğum bir widget çağırıyorum kod temizliği olması açısından getter yapıp o şekilde çağırmıştım buradaki eksiğimi tam olarak anlayamadım.Aşağıda eklediğim gibi sayfanın en altında
```
  CustomAppBar get _buildAppBar => CustomAppBar(
        title: AutoSizeText(
          AppConstants.homeAppBar.tr,
          maxFontSize: 35,
          minFontSize: 25,
          style: AppTextStyle.appBarTextStyle,
        ),
        showLeadingBackIcon: false,
        onLeadingPressed: () {},
        actions: const [],
      );
```

2.Aslında 1. de bu maddeye bir açıklama ilettim ama burada da diyeyim component olarak modules->common->widgets->appBar altında bulunuyor.

3.Normalde değerleri static getter olarak tanımlanıştım num extension yapınca performansın daha da artabileceğini bilmiyordum ve düşününce kullanımı daha işlevsel olur teşekkürler artık bu şekilde kullanacağım.

**Comment by batuhanozkandev** [comment]
> İncelemen için çok teşekkürler madde madde ilerleyip açıklama yapacağım.Aslında bu proje benim ilk flutter projelerim arasında dönüp baktığımda eksiklerime gülüyorum bazen ne kadar yol kat ettiğimi görüyorum tabikide hala bilmediğim taraflar var ve incelemen bu konuda benim için yararlı oldu tekrardan teşekkürler.
> 
> 1. Dediğin gibi aslında CustomAppBar olarak dışardan oluşturduğum bir widget çağırıyorum kod temizliği olması açısından getter yapıp o şekilde çağırmıştım buradaki eksiğimi tam olarak anlayamadım.Aşağıda eklediğim gibi sayfanın en altında
> 
> ```
>   CustomAppBar get _buildAppBar => CustomAppBar(
>         title: AutoSizeText(
>           AppConstants.homeAppBar.tr,
>           maxFontSize: 35,
>           minFontSize: 25,
>           style: AppTextStyle.appBarTextStyle,
>         ),
>         showLeadingBackIcon: false,
>         onLeadingPressed: () {},
>         actions: const [],
>       );
> ```
> 
> 2.Aslında 1. de bu maddeye bir açıklama ilettim ama burada da diyeyim component olarak modules->common->widgets->appBar altında bulunuyor.
> 
> 3.Normalde değerleri static getter olarak tanımlanıştım num extension yapınca performansın daha da artabileceğini bilmiyordum ve düşününce kullanımı daha işlevsel olur teşekkürler artık bu şekilde kullanacağım.

AppBar'ı getter olarak kullanmak güzel bir düşünce ama bunu neredeyse her sayfanın altında yaptığın zaman çok kod tekrarı yapmış olursun ve ileride örneğin app barın rengini değiştirmek istediğinde bütün sayfalardaki bu getter methodunu değiştirmekle zaman kaybedeceksin. Onun yerine bunu bir model haline getirirsen senin için daha rahat olur diye düşünüyorum.
